### ISSUE TITLE
Update to Bevy 0.10

### ISSUE THREAD

**Issue by Andrewp2** [Andrewp2/bevy_camera_shake#2]
(when it comes out)

**Comment by Andrewp2** [comment]
In progress

**Comment by Andrewp2** [comment]
Done! https://github.com/Andrewp2/bevy_camera_shake/commit/f3f085d80660a0a36b467b942fc0de675f2c77f8

**Comment by musjj** [comment]
Any chance of updating this for 0.11?

**Comment by Andrewp2** [comment]
@musjj Updated for 0.11

**Comment by musjj** [comment]
Thank you!
